import { Surface, RunningStyle, PastResult, TrackCondition } from '@/types'

type RawHorse = {
  number: number
  gate: number
  name: string
  jockey: string
  trainer: string
  age: number
  sex: string
  winOdds: number
  placeOddsMin: number
  placeOddsMax: number
  popularity: number
  style: RunningStyle
  pastResults: PastResult[]
}

type RawRace = {
  id: string
  date: string
  venue: string
  raceNumber: number
  raceName: string
  distance: number
  surface: Surface
  grade: string
  trackCondition: TrackCondition
  horses: RawHorse[]
}

export function getMockRaces(): RawRace[] {
  return [
    // Race 1: 東京11R G1 天皇賞（春）
    {
      id: 'race-20260508-tokyo-11',
      date: '2026-05-08',
      venue: '東京',
      raceNumber: 11,
      raceName: '天皇賞（春）',
      distance: 3200,
      surface: '芝',
      grade: 'G1',
      trackCondition: '良',
      horses: [
        {
          number: 1,
          gate: 1,
          name: 'ディープスカイブルー',
          jockey: '川田将雅',
          trainer: '矢作芳人',
          age: 5,
          sex: '牡',
          winOdds: 2.4,
          placeOddsMin: 1.1,
          placeOddsMax: 1.5,
          popularity: 1,
          style: '先行',
          pastResults: [
            { venue: '阪神', distance: 3000, surface: '芝', position: 1, total: 12 },
            { venue: '中山', distance: 2500, surface: '芝', position: 1, total: 10 },
            { venue: '東京', distance: 2400, surface: '芝', position: 2, total: 14 },
            { venue: '阪神', distance: 2200, surface: '芝', position: 1, total: 11 },
            { venue: '東京', distance: 3200, surface: '芝', position: 2, total: 12 },
          ],
        },
        {
          number: 2,
          gate: 1,
          name: 'ゴールデンフォース',
          jockey: '福永祐一',
          trainer: '池江泰寿',
          age: 6,
          sex: '牡',
          winOdds: 4.1,
          placeOddsMin: 1.3,
          placeOddsMax: 2.0,
          popularity: 2,
          style: '差し',
          pastResults: [
            { venue: '京都', distance: 3200, surface: '芝', position: 1, total: 13 },
            { venue: '阪神', distance: 3000, surface: '芝', position: 3, total: 12 },
            { venue: '東京', distance: 2400, surface: '芝', position: 2, total: 14 },
            { venue: '中山', distance: 2500, surface: '芝', position: 1, total: 10 },
            { venue: '東京', distance: 3200, surface: '芝', position: 3, total: 11 },
          ],
        },
        {
          number: 3,
          gate: 2,
          name: 'サクラエンペラー',
          jockey: '戸崎圭太',
          trainer: '国枝栄',
          age: 5,
          sex: '牡',
          winOdds: 7.8,
          placeOddsMin: 2.1,
          placeOddsMax: 3.5,
          popularity: 3,
          style: '追込',
          pastResults: [
            { venue: '東京', distance: 2400, surface: '芝', position: 2, total: 14 },
            { venue: '中山', distance: 2200, surface: '芝', position: 1, total: 11 },
            { venue: '阪神', distance: 3000, surface: '芝', position: 4, total: 12 },
            { venue: '東京', distance: 3200, surface: '芝', position: 5, total: 12 },
            { venue: '京都', distance: 2800, surface: '芝', position: 2, total: 10 },
          ],
        },
        {
          number: 4,
          gate: 2,
          name: 'ミッドナイトストーム',
          jockey: '松山弘平',
          trainer: '角居勝彦',
          age: 6,
          sex: '牡',
          winOdds: 12.5,
          placeOddsMin: 3.2,
          placeOddsMax: 5.5,
          popularity: 4,
          style: '先行',
          pastResults: [
            { venue: '阪神', distance: 3000, surface: '芝', position: 3, total: 12 },
            { venue: '東京', distance: 2400, surface: '芝', position: 5, total: 14 },
            { venue: '中山', distance: 2500, surface: '芝', position: 2, total: 10 },
            { venue: '東京', distance: 3200, surface: '芝', position: 4, total: 12 },
            { venue: '阪神', distance: 2200, surface: '芝', position: 3, total: 11 },
          ],
        },
        {
          number: 5,
          gate: 3,
          name: 'テイエムレジェンド',
          jockey: '岩田康誠',
          trainer: '西浦勝一',
          age: 7,
          sex: '牡',
          winOdds: 18.0,
          placeOddsMin: 4.5,
          placeOddsMax: 7.5,
          popularity: 5,
          style: '逃げ',
          pastResults: [
            { venue: '京都', distance: 3200, surface: '芝', position: 4, total: 13 },
            { venue: '阪神', distance: 3000, surface: '芝', position: 6, total: 12 },
            { venue: '東京', distance: 3200, surface: '芝', position: 3, total: 12 },
            { venue: '中山', distance: 2500, surface: '芝', position: 5, total: 10 },
          ],
        },
        {
          number: 6,
          gate: 3,
          name: 'アルファロメオ',
          jockey: '横山武史',
          trainer: '堀宣行',
          age: 4,
          sex: '牡',
          winOdds: 25.0,
          placeOddsMin: 6.0,
          placeOddsMax: 10.0,
          popularity: 6,
          style: '差し',
          pastResults: [
            { venue: '東京', distance: 2400, surface: '芝', position: 1, total: 14 },
            { venue: '阪神', distance: 2200, surface: '芝', position: 2, total: 11 },
            { venue: '中山', distance: 2200, surface: '芝', position: 3, total: 12 },
            { venue: '東京', distance: 2000, surface: '芝', position: 6, total: 16 },
          ],
        },
        {
          number: 7,
          gate: 4,
          name: 'シルバームーン',
          jockey: '浜中俊',
          trainer: '藤原英昭',
          age: 5,
          sex: '牝',
          winOdds: 38.0,
          placeOddsMin: 8.0,
          placeOddsMax: 15.0,
          popularity: 7,
          style: '追込',
          pastResults: [
            { venue: '阪神', distance: 3000, surface: '芝', position: 5, total: 12 },
            { venue: '京都', distance: 2800, surface: '芝', position: 3, total: 10 },
            { venue: '東京', distance: 2400, surface: '芝', position: 7, total: 14 },
            { venue: '阪神', distance: 2200, surface: '芝', position: 4, total: 11 },
            { venue: '中山', distance: 2500, surface: '芝', position: 6, total: 10 },
          ],
        },
        {
          number: 8,
          gate: 4,
          name: 'ダイナミックウェーブ',
          jockey: '北村友一',
          trainer: '音無秀孝',
          age: 6,
          sex: '牡',
          winOdds: 55.0,
          placeOddsMin: 12.0,
          placeOddsMax: 20.0,
          popularity: 8,
          style: '先行',
          pastResults: [
            { venue: '中山', distance: 2500, surface: '芝', position: 6, total: 10 },
            { venue: '東京', distance: 3200, surface: '芝', position: 8, total: 12 },
            { venue: '阪神', distance: 3000, surface: '芝', position: 7, total: 12 },
            { venue: '京都', distance: 3200, surface: '芝', position: 5, total: 13 },
          ],
        },
        {
          number: 9,
          gate: 5,
          name: 'フジノモンスター',
          jockey: '田辺裕信',
          trainer: '高野友和',
          age: 5,
          sex: '牡',
          winOdds: 72.0,
          placeOddsMin: 16.0,
          placeOddsMax: 30.0,
          popularity: 9,
          style: '差し',
          pastResults: [
            { venue: '東京', distance: 2400, surface: '芝', position: 8, total: 14 },
            { venue: '阪神', distance: 2200, surface: '芝', position: 6, total: 11 },
            { venue: '中山', distance: 2500, surface: '芝', position: 7, total: 10 },
          ],
        },
      ],
    },

    // Race 2: 京都9R オープン競走
    {
      id: 'race-20260508-kyoto-9',
      date: '2026-05-08',
      venue: '京都',
      raceNumber: 9,
      raceName: '葵ステークス',
      distance: 1200,
      surface: '芝',
      grade: 'OP',
      trackCondition: '稍重',
      horses: [
        {
          number: 1,
          gate: 1,
          name: 'ライトニングボルト',
          jockey: '武豊',
          trainer: '橋田満',
          age: 3,
          sex: '牡',
          winOdds: 3.2,
          placeOddsMin: 1.2,
          placeOddsMax: 1.8,
          popularity: 1,
          style: '逃げ',
          pastResults: [
            { venue: '阪神', distance: 1200, surface: '芝', position: 1, total: 10 },
            { venue: '中京', distance: 1200, surface: '芝', position: 1, total: 12 },
            { venue: '京都', distance: 1400, surface: '芝', position: 2, total: 11 },
            { venue: '阪神', distance: 1200, surface: '芝', position: 1, total: 10 },
          ],
        },
        {
          number: 2,
          gate: 1,
          name: 'クリスタルウィング',
          jockey: '川田将雅',
          trainer: '矢作芳人',
          age: 3,
          sex: '牝',
          winOdds: 4.8,
          placeOddsMin: 1.5,
          placeOddsMax: 2.5,
          popularity: 2,
          style: '先行',
          pastResults: [
            { venue: '京都', distance: 1200, surface: '芝', position: 2, total: 12 },
            { venue: '阪神', distance: 1400, surface: '芝', position: 1, total: 11 },
            { venue: '中京', distance: 1200, surface: '芝', position: 1, total: 10 },
            { venue: '東京', distance: 1400, surface: '芝', position: 3, total: 14 },
            { venue: '京都', distance: 1200, surface: '芝', position: 2, total: 12 },
          ],
        },
        {
          number: 3,
          gate: 2,
          name: 'ヴェルデカラー',
          jockey: '福永祐一',
          trainer: '池江泰寿',
          age: 3,
          sex: '牡',
          winOdds: 8.5,
          placeOddsMin: 2.3,
          placeOddsMax: 4.0,
          popularity: 3,
          style: '差し',
          pastResults: [
            { venue: '阪神', distance: 1200, surface: '芝', position: 3, total: 10 },
            { venue: '京都', distance: 1200, surface: '芝', position: 1, total: 12 },
            { venue: '中京', distance: 1400, surface: '芝', position: 4, total: 12 },
            { venue: '阪神', distance: 1200, surface: '芝', position: 2, total: 10 },
          ],
        },
        {
          number: 4,
          gate: 2,
          name: 'スプリントキング',
          jockey: '戸崎圭太',
          trainer: '国枝栄',
          age: 4,
          sex: '牡',
          winOdds: 11.0,
          placeOddsMin: 3.0,
          placeOddsMax: 5.5,
          popularity: 4,
          style: '逃げ',
          pastResults: [
            { venue: '中京', distance: 1200, surface: '芝', position: 2, total: 12 },
            { venue: '阪神', distance: 1200, surface: '芝', position: 4, total: 10 },
            { venue: '京都', distance: 1200, surface: '芝', position: 3, total: 12 },
            { venue: '中山', distance: 1200, surface: '芝', position: 1, total: 11 },
            { venue: '阪神', distance: 1200, surface: '芝', position: 5, total: 10 },
          ],
        },
        {
          number: 5,
          gate: 3,
          name: 'ホットスパーク',
          jockey: '松山弘平',
          trainer: '角居勝彦',
          age: 3,
          sex: '牡',
          winOdds: 16.0,
          placeOddsMin: 4.0,
          placeOddsMax: 7.0,
          popularity: 5,
          style: '先行',
          pastResults: [
            { venue: '阪神', distance: 1200, surface: '芝', position: 5, total: 10 },
            { venue: '京都', distance: 1400, surface: '芝', position: 2, total: 11 },
            { venue: '中京', distance: 1200, surface: '芝', position: 3, total: 12 },
            { venue: '阪神', distance: 1200, surface: '芝', position: 4, total: 10 },
          ],
        },
        {
          number: 6,
          gate: 3,
          name: 'フラッシュダンサー',
          jockey: '岩田康誠',
          trainer: '西浦勝一',
          age: 3,
          sex: '牝',
          winOdds: 22.0,
          placeOddsMin: 5.5,
          placeOddsMax: 9.5,
          popularity: 6,
          style: '差し',
          pastResults: [
            { venue: '京都', distance: 1200, surface: '芝', position: 4, total: 12 },
            { venue: '阪神', distance: 1400, surface: '芝', position: 3, total: 11 },
            { venue: '中京', distance: 1200, surface: '芝', position: 6, total: 12 },
            { venue: '阪神', distance: 1200, surface: '芝', position: 2, total: 10 },
            { venue: '東京', distance: 1400, surface: '芝', position: 5, total: 14 },
          ],
        },
        {
          number: 7,
          gate: 4,
          name: 'サンダークラップ',
          jockey: '横山武史',
          trainer: '堀宣行',
          age: 4,
          sex: '牡',
          winOdds: 35.0,
          placeOddsMin: 8.0,
          placeOddsMax: 14.0,
          popularity: 7,
          style: '追込',
          pastResults: [
            { venue: '中山', distance: 1200, surface: '芝', position: 6, total: 11 },
            { venue: '阪神', distance: 1200, surface: '芝', position: 7, total: 10 },
            { venue: '京都', distance: 1200, surface: '芝', position: 5, total: 12 },
            { venue: '中京', distance: 1200, surface: '芝', position: 3, total: 12 },
          ],
        },
        {
          number: 8,
          gate: 4,
          name: 'ネオジェネシス',
          jockey: '浜中俊',
          trainer: '藤原英昭',
          age: 3,
          sex: '牡',
          winOdds: 48.0,
          placeOddsMin: 11.0,
          placeOddsMax: 18.0,
          popularity: 8,
          style: '先行',
          pastResults: [
            { venue: '阪神', distance: 1200, surface: '芝', position: 8, total: 10 },
            { venue: '京都', distance: 1400, surface: '芝', position: 5, total: 11 },
            { venue: '中京', distance: 1200, surface: '芝', position: 4, total: 12 },
          ],
        },
      ],
    },

    // Race 3: 新潟5R 1勝クラス
    {
      id: 'race-20260508-niigata-5',
      date: '2026-05-08',
      venue: '新潟',
      raceNumber: 5,
      raceName: '1勝クラス（ダート1800m）',
      distance: 1800,
      surface: 'ダート',
      grade: '1勝クラス',
      trackCondition: '重',
      horses: [
        {
          number: 1,
          gate: 1,
          name: 'ブルーオーシャン',
          jockey: '吉田隼人',
          trainer: '奥村武',
          age: 4,
          sex: '牡',
          winOdds: 2.8,
          placeOddsMin: 1.1,
          placeOddsMax: 1.6,
          popularity: 1,
          style: '先行',
          pastResults: [
            { venue: '新潟', distance: 1800, surface: 'ダート', position: 1, total: 9 },
            { venue: '中山', distance: 1800, surface: 'ダート', position: 2, total: 10 },
            { venue: '東京', distance: 1600, surface: 'ダート', position: 1, total: 11 },
            { venue: '新潟', distance: 1800, surface: 'ダート', position: 3, total: 9 },
            { venue: '中山', distance: 2100, surface: 'ダート', position: 2, total: 10 },
          ],
        },
        {
          number: 2,
          gate: 1,
          name: 'グランドスラム',
          jockey: '田辺裕信',
          trainer: '高野友和',
          age: 5,
          sex: '牡',
          winOdds: 5.5,
          placeOddsMin: 1.8,
          placeOddsMax: 3.0,
          popularity: 2,
          style: '逃げ',
          pastResults: [
            { venue: '中山', distance: 1800, surface: 'ダート', position: 1, total: 10 },
            { venue: '新潟', distance: 1800, surface: 'ダート', position: 2, total: 9 },
            { venue: '東京', distance: 1600, surface: 'ダート', position: 4, total: 11 },
            { venue: '中山', distance: 2100, surface: 'ダート', position: 1, total: 10 },
          ],
        },
        {
          number: 3,
          gate: 2,
          name: 'アイアンフィスト',
          jockey: '北村友一',
          trainer: '音無秀孝',
          age: 4,
          sex: '牡',
          winOdds: 9.0,
          placeOddsMin: 2.5,
          placeOddsMax: 4.5,
          popularity: 3,
          style: '差し',
          pastResults: [
            { venue: '東京', distance: 1600, surface: 'ダート', position: 2, total: 11 },
            { venue: '中山', distance: 1800, surface: 'ダート', position: 3, total: 10 },
            { venue: '新潟', distance: 1800, surface: 'ダート', position: 4, total: 9 },
            { venue: '東京', distance: 2100, surface: 'ダート', position: 2, total: 10 },
            { venue: '中山', distance: 1800, surface: 'ダート', position: 5, total: 10 },
          ],
        },
        {
          number: 4,
          gate: 2,
          name: 'サイレントハンター',
          jockey: '松若風馬',
          trainer: '清水久詞',
          age: 5,
          sex: '牡',
          winOdds: 13.0,
          placeOddsMin: 3.5,
          placeOddsMax: 6.5,
          popularity: 4,
          style: '先行',
          pastResults: [
            { venue: '新潟', distance: 1800, surface: 'ダート', position: 3, total: 9 },
            { venue: '東京', distance: 1600, surface: 'ダート', position: 5, total: 11 },
            { venue: '中山', distance: 1800, surface: 'ダート', position: 2, total: 10 },
            { venue: '新潟', distance: 1800, surface: 'ダート', position: 6, total: 9 },
          ],
        },
        {
          number: 5,
          gate: 3,
          name: 'ロードウォリアー',
          jockey: '幸英明',
          trainer: '石坂正',
          age: 6,
          sex: '牡',
          winOdds: 19.0,
          placeOddsMin: 5.0,
          placeOddsMax: 9.0,
          popularity: 5,
          style: '追込',
          pastResults: [
            { venue: '中山', distance: 2100, surface: 'ダート', position: 4, total: 10 },
            { venue: '新潟', distance: 1800, surface: 'ダート', position: 5, total: 9 },
            { venue: '東京', distance: 1600, surface: 'ダート', position: 3, total: 11 },
            { venue: '中山', distance: 1800, surface: 'ダート', position: 4, total: 10 },
            { venue: '新潟', distance: 1800, surface: 'ダート', position: 2, total: 9 },
          ],
        },
        {
          number: 6,
          gate: 3,
          name: 'スタームーン',
          jockey: '西村淳也',
          trainer: '斉藤崇史',
          age: 4,
          sex: '牝',
          winOdds: 28.0,
          placeOddsMin: 7.0,
          placeOddsMax: 12.0,
          popularity: 6,
          style: '先行',
          pastResults: [
            { venue: '東京', distance: 1600, surface: 'ダート', position: 6, total: 11 },
            { venue: '新潟', distance: 1800, surface: 'ダート', position: 4, total: 9 },
            { venue: '中山', distance: 1800, surface: 'ダート', position: 3, total: 10 },
          ],
        },
        {
          number: 7,
          gate: 4,
          name: 'ワイルドカード',
          jockey: '藤岡佑介',
          trainer: '大根田裕之',
          age: 5,
          sex: '牡',
          winOdds: 42.0,
          placeOddsMin: 9.5,
          placeOddsMax: 18.0,
          popularity: 7,
          style: '逃げ',
          pastResults: [
            { venue: '新潟', distance: 1800, surface: 'ダート', position: 7, total: 9 },
            { venue: '中山', distance: 1800, surface: 'ダート', position: 6, total: 10 },
            { venue: '東京', distance: 2100, surface: 'ダート', position: 5, total: 10 },
            { venue: '新潟', distance: 1800, surface: 'ダート', position: 8, total: 9 },
          ],
        },
        {
          number: 8,
          gate: 4,
          name: 'ドリームチェイサー',
          jockey: '秋山真一郎',
          trainer: '小島茂之',
          age: 4,
          sex: '牡',
          winOdds: 65.0,
          placeOddsMin: 14.0,
          placeOddsMax: 26.0,
          popularity: 8,
          style: '差し',
          pastResults: [
            { venue: '中山', distance: 1800, surface: 'ダート', position: 8, total: 10 },
            { venue: '東京', distance: 1600, surface: 'ダート', position: 7, total: 11 },
            { venue: '新潟', distance: 1800, surface: 'ダート', position: 6, total: 9 },
          ],
        },
        {
          number: 9,
          gate: 5,
          name: 'フェニックスライズ',
          jockey: '丹内祐次',
          trainer: '武市康男',
          age: 6,
          sex: '牡',
          winOdds: 80.0,
          placeOddsMin: 18.0,
          placeOddsMax: 35.0,
          popularity: 9,
          style: '追込',
          pastResults: [
            { venue: '新潟', distance: 1800, surface: 'ダート', position: 9, total: 9 },
            { venue: '中山', distance: 2100, surface: 'ダート', position: 7, total: 10 },
            { venue: '東京', distance: 1600, surface: 'ダート', position: 8, total: 11 },
          ],
        },
      ],
    },

    // Race 4: 東京4R 未勝利
    {
      id: 'race-20260508-tokyo-4',
      date: '2026-05-08',
      venue: '東京',
      raceNumber: 4,
      raceName: '未勝利（芝1600m）',
      distance: 1600,
      surface: '芝',
      grade: '未勝利',
      trackCondition: '良',
      horses: [
        {
          number: 1,
          gate: 1,
          name: 'プレミアムスター',
          jockey: '横山典弘',
          trainer: '萩原清',
          age: 3,
          sex: '牝',
          winOdds: 3.5,
          placeOddsMin: 1.2,
          placeOddsMax: 1.9,
          popularity: 1,
          style: '先行',
          pastResults: [
            { venue: '東京', distance: 1600, surface: '芝', position: 2, total: 13 },
            { venue: '阪神', distance: 1600, surface: '芝', position: 2, total: 12 },
            { venue: '東京', distance: 1400, surface: '芝', position: 3, total: 14 },
            { venue: '中山', distance: 1600, surface: '芝', position: 2, total: 12 },
          ],
        },
        {
          number: 2,
          gate: 1,
          name: 'ナイトブルーム',
          jockey: '柴田善臣',
          trainer: '小崎憲',
          age: 3,
          sex: '牡',
          winOdds: 5.2,
          placeOddsMin: 1.7,
          placeOddsMax: 2.8,
          popularity: 2,
          style: '差し',
          pastResults: [
            { venue: '東京', distance: 1600, surface: '芝', position: 3, total: 13 },
            { venue: '中山', distance: 1800, surface: '芝', position: 2, total: 11 },
            { venue: '東京', distance: 1400, surface: '芝', position: 4, total: 14 },
            { venue: '阪神', distance: 1600, surface: '芝', position: 3, total: 12 },
            { venue: '東京', distance: 1600, surface: '芝', position: 2, total: 13 },
          ],
        },
        {
          number: 3,
          gate: 2,
          name: 'エメラルドドリーム',
          jockey: '内田博幸',
          trainer: '二ノ宮敬宇',
          age: 3,
          sex: '牝',
          winOdds: 9.5,
          placeOddsMin: 2.6,
          placeOddsMax: 4.8,
          popularity: 3,
          style: '先行',
          pastResults: [
            { venue: '阪神', distance: 1600, surface: '芝', position: 1, total: 12 },
            { venue: '東京', distance: 1600, surface: '芝', position: 4, total: 13 },
            { venue: '中山', distance: 1600, surface: '芝', position: 3, total: 12 },
            { venue: '東京', distance: 1400, surface: '芝', position: 5, total: 14 },
          ],
        },
        {
          number: 4,
          gate: 2,
          name: 'ホワイトダイヤモンド',
          jockey: '蛯名正義',
          trainer: '伊藤正徳',
          age: 3,
          sex: '牡',
          winOdds: 14.0,
          placeOddsMin: 3.8,
          placeOddsMax: 7.0,
          popularity: 4,
          style: '逃げ',
          pastResults: [
            { venue: '東京', distance: 1400, surface: '芝', position: 2, total: 14 },
            { venue: '中山', distance: 1600, surface: '芝', position: 5, total: 12 },
            { venue: '東京', distance: 1600, surface: '芝', position: 5, total: 13 },
            { venue: '阪神', distance: 1400, surface: '芝', position: 3, total: 12 },
            { venue: '東京', distance: 1600, surface: '芝', position: 4, total: 13 },
          ],
        },
        {
          number: 5,
          gate: 3,
          name: 'マジックアロー',
          jockey: '藤岡康太',
          trainer: '加藤征弘',
          age: 3,
          sex: '牡',
          winOdds: 20.0,
          placeOddsMin: 5.2,
          placeOddsMax: 9.5,
          popularity: 5,
          style: '差し',
          pastResults: [
            { venue: '中山', distance: 1600, surface: '芝', position: 4, total: 12 },
            { venue: '東京', distance: 1600, surface: '芝', position: 6, total: 13 },
            { venue: '阪神', distance: 1400, surface: '芝', position: 4, total: 12 },
            { venue: '東京', distance: 1400, surface: '芝', position: 6, total: 14 },
          ],
        },
        {
          number: 6,
          gate: 3,
          name: 'リュミエールブレイン',
          jockey: '三浦皇成',
          trainer: '鈴木伸尋',
          age: 3,
          sex: '牝',
          winOdds: 30.0,
          placeOddsMin: 7.5,
          placeOddsMax: 14.0,
          popularity: 6,
          style: '追込',
          pastResults: [
            { venue: '東京', distance: 1600, surface: '芝', position: 7, total: 13 },
            { venue: '中山', distance: 1800, surface: '芝', position: 3, total: 11 },
            { venue: '阪神', distance: 1600, surface: '芝', position: 5, total: 12 },
            { venue: '東京', distance: 1400, surface: '芝', position: 7, total: 14 },
          ],
        },
        {
          number: 7,
          gate: 4,
          name: 'ターボジェット',
          jockey: '菊沢一樹',
          trainer: '菊沢隆徳',
          age: 3,
          sex: '牡',
          winOdds: 45.0,
          placeOddsMin: 10.0,
          placeOddsMax: 19.0,
          popularity: 7,
          style: '先行',
          pastResults: [
            { venue: '阪神', distance: 1600, surface: '芝', position: 6, total: 12 },
            { venue: '東京', distance: 1600, surface: '芝', position: 8, total: 13 },
            { venue: '中山', distance: 1600, surface: '芝', position: 6, total: 12 },
          ],
        },
        {
          number: 8,
          gate: 4,
          name: 'サニーデイズ',
          jockey: '勝浦正樹',
          trainer: '中竹和也',
          age: 3,
          sex: '牝',
          winOdds: 60.0,
          placeOddsMin: 13.0,
          placeOddsMax: 25.0,
          popularity: 8,
          style: '差し',
          pastResults: [
            { venue: '東京', distance: 1400, surface: '芝', position: 9, total: 14 },
            { venue: '中山', distance: 1600, surface: '芝', position: 7, total: 12 },
            { venue: '東京', distance: 1600, surface: '芝', position: 9, total: 13 },
          ],
        },
        {
          number: 9,
          gate: 5,
          name: 'コスモヴァリアント',
          jockey: '小野寺祐太',
          trainer: '高橋裕',
          age: 3,
          sex: '牡',
          winOdds: 75.0,
          placeOddsMin: 16.0,
          placeOddsMax: 32.0,
          popularity: 9,
          style: '追込',
          pastResults: [
            { venue: '阪神', distance: 1600, surface: '芝', position: 8, total: 12 },
            { venue: '東京', distance: 1600, surface: '芝', position: 10, total: 13 },
          ],
        },
        {
          number: 10,
          gate: 5,
          name: 'ラッキーチャーム',
          jockey: '吉田豊',
          trainer: '菅原泰夫',
          age: 3,
          sex: '牝',
          winOdds: 85.0,
          placeOddsMin: 19.0,
          placeOddsMax: 40.0,
          popularity: 10,
          style: '先行',
          pastResults: [
            { venue: '東京', distance: 1600, surface: '芝', position: 11, total: 13 },
            { venue: '中山', distance: 1600, surface: '芝', position: 9, total: 12 },
          ],
        },
      ],
    },
  ]
}
